// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: remote_user_svc.proto

package appcontextsvc_client

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _remote_user_svc_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on GetProfilePhotoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetProfilePhotoRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetProfilePhotoRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetProfilePhotoRequestMultiError, or nil if none found.
func (m *GetProfilePhotoRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetProfilePhotoRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserprofileId() != "" {

		if err := m._validateUuid(m.GetUserprofileId()); err != nil {
			err = GetProfilePhotoRequestValidationError{
				field:  "UserprofileId",
				reason: "value must be a valid UUID",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.GetOriginId() != "" {

		if err := m._validateUuid(m.GetOriginId()); err != nil {
			err = GetProfilePhotoRequestValidationError{
				field:  "OriginId",
				reason: "value must be a valid UUID",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.GetRemoteConnectionId() != "" {

		if err := m._validateUuid(m.GetRemoteConnectionId()); err != nil {
			err = GetProfilePhotoRequestValidationError{
				field:  "RemoteConnectionId",
				reason: "value must be a valid UUID",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return GetProfilePhotoRequestMultiError(errors)
	}

	return nil
}

func (m *GetProfilePhotoRequest) _validateUuid(uuid string) error {
	if matched := _remote_user_svc_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetProfilePhotoRequestMultiError is an error wrapping multiple validation
// errors returned by GetProfilePhotoRequest.ValidateAll() if the designated
// constraints aren't met.
type GetProfilePhotoRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetProfilePhotoRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetProfilePhotoRequestMultiError) AllErrors() []error { return m }

// GetProfilePhotoRequestValidationError is the validation error returned by
// GetProfilePhotoRequest.Validate if the designated constraints aren't met.
type GetProfilePhotoRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetProfilePhotoRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetProfilePhotoRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetProfilePhotoRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetProfilePhotoRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetProfilePhotoRequestValidationError) ErrorName() string {
	return "GetProfilePhotoRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetProfilePhotoRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetProfilePhotoRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetProfilePhotoRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetProfilePhotoRequestValidationError{}

// Validate checks the field values on ListRemoteUsersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRemoteUsersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRemoteUsersResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRemoteUsersResponseMultiError, or nil if none found.
func (m *ListRemoteUsersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRemoteUsersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRemoteUsers() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListRemoteUsersResponseValidationError{
						field:  fmt.Sprintf("RemoteUsers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListRemoteUsersResponseValidationError{
						field:  fmt.Sprintf("RemoteUsers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListRemoteUsersResponseValidationError{
					field:  fmt.Sprintf("RemoteUsers[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for PageNumber

	// no validation rules for PageSize

	// no validation rules for TotalCount

	if len(errors) > 0 {
		return ListRemoteUsersResponseMultiError(errors)
	}

	return nil
}

// ListRemoteUsersResponseMultiError is an error wrapping multiple validation
// errors returned by ListRemoteUsersResponse.ValidateAll() if the designated
// constraints aren't met.
type ListRemoteUsersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRemoteUsersResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRemoteUsersResponseMultiError) AllErrors() []error { return m }

// ListRemoteUsersResponseValidationError is the validation error returned by
// ListRemoteUsersResponse.Validate if the designated constraints aren't met.
type ListRemoteUsersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRemoteUsersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRemoteUsersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRemoteUsersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRemoteUsersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRemoteUsersResponseValidationError) ErrorName() string {
	return "ListRemoteUsersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListRemoteUsersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRemoteUsersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRemoteUsersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRemoteUsersResponseValidationError{}

// Validate checks the field values on GetRemoteUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRemoteUserRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRemoteUserRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRemoteUserRequestMultiError, or nil if none found.
func (m *GetRemoteUserRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRemoteUserRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() != "" {

		if err := m._validateUuid(m.GetId()); err != nil {
			err = GetRemoteUserRequestValidationError{
				field:  "Id",
				reason: "value must be a valid UUID",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if len(errors) > 0 {
		return GetRemoteUserRequestMultiError(errors)
	}

	return nil
}

func (m *GetRemoteUserRequest) _validateUuid(uuid string) error {
	if matched := _remote_user_svc_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetRemoteUserRequestMultiError is an error wrapping multiple validation
// errors returned by GetRemoteUserRequest.ValidateAll() if the designated
// constraints aren't met.
type GetRemoteUserRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRemoteUserRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRemoteUserRequestMultiError) AllErrors() []error { return m }

// GetRemoteUserRequestValidationError is the validation error returned by
// GetRemoteUserRequest.Validate if the designated constraints aren't met.
type GetRemoteUserRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRemoteUserRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRemoteUserRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRemoteUserRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRemoteUserRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRemoteUserRequestValidationError) ErrorName() string {
	return "GetRemoteUserRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetRemoteUserRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRemoteUserRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRemoteUserRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRemoteUserRequestValidationError{}
