// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: models/asset_seating.proto

package models

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _asset_seating_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on AssetSeating with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AssetSeating) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AssetSeating with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AssetSeatingMultiError, or
// nil if none found.
func (m *AssetSeating) ValidateAll() error {
	return m.validate(true)
}

func (m *AssetSeating) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetAssetId() != "" {

		if err := m._validateUuid(m.GetAssetId()); err != nil {
			err = AssetSeatingValidationError{
				field:  "AssetId",
				reason: "value must be a valid UUID",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.GetSeatingId() != "" {

		if err := m._validateUuid(m.GetSeatingId()); err != nil {
			err = AssetSeatingValidationError{
				field:  "SeatingId",
				reason: "value must be a valid UUID",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.Capacity != nil {
		// no validation rules for Capacity
	}

	if m.IsDefault != nil {
		// no validation rules for IsDefault
	}

	if len(errors) > 0 {
		return AssetSeatingMultiError(errors)
	}

	return nil
}

func (m *AssetSeating) _validateUuid(uuid string) error {
	if matched := _asset_seating_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// AssetSeatingMultiError is an error wrapping multiple validation errors
// returned by AssetSeating.ValidateAll() if the designated constraints aren't met.
type AssetSeatingMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AssetSeatingMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AssetSeatingMultiError) AllErrors() []error { return m }

// AssetSeatingValidationError is the validation error returned by
// AssetSeating.Validate if the designated constraints aren't met.
type AssetSeatingValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AssetSeatingValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AssetSeatingValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AssetSeatingValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AssetSeatingValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AssetSeatingValidationError) ErrorName() string { return "AssetSeatingValidationError" }

// Error satisfies the builtin error interface
func (e AssetSeatingValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAssetSeating.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AssetSeatingValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AssetSeatingValidationError{}
