// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: models/favorite.proto

package models

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _favorite_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Favorite with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Favorite) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Favorite with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in FavoriteMultiError, or nil
// if none found.
func (m *Favorite) ValidateAll() error {
	return m.validate(true)
}

func (m *Favorite) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetUserprofileId() != "" {

		if err := m._validateUuid(m.GetUserprofileId()); err != nil {
			err = FavoriteValidationError{
				field:  "UserprofileId",
				reason: "value must be a valid UUID",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	if m.GetEntityId() != "" {

		if err := m._validateUuid(m.GetEntityId()); err != nil {
			err = FavoriteValidationError{
				field:  "EntityId",
				reason: "value must be a valid UUID",
				cause:  err,
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

	}

	// no validation rules for EntityType

	if m.Id != nil {

		if m.GetId() != "" {

			if err := m._validateUuid(m.GetId()); err != nil {
				err = FavoriteValidationError{
					field:  "Id",
					reason: "value must be a valid UUID",
					cause:  err,
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if m.TenantId != nil {

		if m.GetTenantId() != "" {

			if err := m._validateUuid(m.GetTenantId()); err != nil {
				err = FavoriteValidationError{
					field:  "TenantId",
					reason: "value must be a valid UUID",
					cause:  err,
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if len(errors) > 0 {
		return FavoriteMultiError(errors)
	}

	return nil
}

func (m *Favorite) _validateUuid(uuid string) error {
	if matched := _favorite_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// FavoriteMultiError is an error wrapping multiple validation errors returned
// by Favorite.ValidateAll() if the designated constraints aren't met.
type FavoriteMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FavoriteMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FavoriteMultiError) AllErrors() []error { return m }

// FavoriteValidationError is the validation error returned by
// Favorite.Validate if the designated constraints aren't met.
type FavoriteValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FavoriteValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FavoriteValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FavoriteValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FavoriteValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FavoriteValidationError) ErrorName() string { return "FavoriteValidationError" }

// Error satisfies the builtin error interface
func (e FavoriteValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFavorite.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FavoriteValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FavoriteValidationError{}
