// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: models/remote_user.proto

package models

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on RemoteUser with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RemoteUser) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoteUser with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RemoteUserMultiError, or
// nil if none found.
func (m *RemoteUser) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoteUser) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for City

	// no validation rules for Country

	// no validation rules for Email

	// no validation rules for Firstname

	// no validation rules for Lastname

	// no validation rules for PhoneNumber

	// no validation rules for Function

	// no validation rules for Division

	// no validation rules for Department

	// no validation rules for Street

	// no validation rules for ZipCode

	// no validation rules for RemoteConnectionId

	if len(errors) > 0 {
		return RemoteUserMultiError(errors)
	}

	return nil
}

// RemoteUserMultiError is an error wrapping multiple validation errors
// returned by RemoteUser.ValidateAll() if the designated constraints aren't met.
type RemoteUserMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoteUserMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoteUserMultiError) AllErrors() []error { return m }

// RemoteUserValidationError is the validation error returned by
// RemoteUser.Validate if the designated constraints aren't met.
type RemoteUserValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoteUserValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoteUserValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoteUserValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoteUserValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoteUserValidationError) ErrorName() string { return "RemoteUserValidationError" }

// Error satisfies the builtin error interface
func (e RemoteUserValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoteUser.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoteUserValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoteUserValidationError{}

// Validate checks the field values on ProfilePhoto with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ProfilePhoto) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProfilePhoto with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ProfilePhotoMultiError, or
// nil if none found.
func (m *ProfilePhoto) ValidateAll() error {
	return m.validate(true)
}

func (m *ProfilePhoto) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for MimeType

	// no validation rules for Image

	if len(errors) > 0 {
		return ProfilePhotoMultiError(errors)
	}

	return nil
}

// ProfilePhotoMultiError is an error wrapping multiple validation errors
// returned by ProfilePhoto.ValidateAll() if the designated constraints aren't met.
type ProfilePhotoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProfilePhotoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProfilePhotoMultiError) AllErrors() []error { return m }

// ProfilePhotoValidationError is the validation error returned by
// ProfilePhoto.Validate if the designated constraints aren't met.
type ProfilePhotoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProfilePhotoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProfilePhotoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProfilePhotoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProfilePhotoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProfilePhotoValidationError) ErrorName() string { return "ProfilePhotoValidationError" }

// Error satisfies the builtin error interface
func (e ProfilePhotoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProfilePhoto.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProfilePhotoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProfilePhotoValidationError{}
