// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: models/remote_asset.proto

package models

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _remote_asset_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on RemoteAsset with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RemoteAsset) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoteAsset with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RemoteAssetMultiError, or
// nil if none found.
func (m *RemoteAsset) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoteAsset) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Upn

	if m.Id != nil {
		// no validation rules for Id
	}

	if m.Name != nil {
		// no validation rules for Name
	}

	if m.City != nil {
		// no validation rules for City
	}

	if m.Country != nil {
		// no validation rules for Country
	}

	if m.Email != nil {
		// no validation rules for Email
	}

	if m.Street != nil {
		// no validation rules for Street
	}

	if m.State != nil {
		// no validation rules for State
	}

	if m.ZipCode != nil {
		// no validation rules for ZipCode
	}

	if m.Capacity != nil {
		// no validation rules for Capacity
	}

	if m.RemoteConnectionId != nil {

		if m.GetRemoteConnectionId() != "" {

			if err := m._validateUuid(m.GetRemoteConnectionId()); err != nil {
				err = RemoteAssetValidationError{
					field:  "RemoteConnectionId",
					reason: "value must be a valid UUID",
					cause:  err,
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if m.AudioDeviceName != nil {
		// no validation rules for AudioDeviceName
	}

	if m.BookingType != nil {
		// no validation rules for BookingType
	}

	if m.Building != nil {
		// no validation rules for Building
	}

	if m.DisplayDeviceName != nil {
		// no validation rules for DisplayDeviceName
	}

	if m.FloorNumber != nil {
		// no validation rules for FloorNumber
	}

	if m.FloorLabel != nil {
		// no validation rules for FloorLabel
	}

	if m.Altitude != nil {
		// no validation rules for Altitude
	}

	if m.Longitude != nil {
		// no validation rules for Longitude
	}

	if m.Latitude != nil {
		// no validation rules for Latitude
	}

	if m.IsWheelChairAccessible != nil {
		// no validation rules for IsWheelChairAccessible
	}

	if m.Label != nil {
		// no validation rules for Label
	}

	if m.Nickname != nil {
		// no validation rules for Nickname
	}

	if m.Phone != nil {
		// no validation rules for Phone
	}

	if m.VideoDeviceName != nil {
		// no validation rules for VideoDeviceName
	}

	if len(errors) > 0 {
		return RemoteAssetMultiError(errors)
	}

	return nil
}

func (m *RemoteAsset) _validateUuid(uuid string) error {
	if matched := _remote_asset_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// RemoteAssetMultiError is an error wrapping multiple validation errors
// returned by RemoteAsset.ValidateAll() if the designated constraints aren't met.
type RemoteAssetMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoteAssetMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoteAssetMultiError) AllErrors() []error { return m }

// RemoteAssetValidationError is the validation error returned by
// RemoteAsset.Validate if the designated constraints aren't met.
type RemoteAssetValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoteAssetValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoteAssetValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoteAssetValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoteAssetValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoteAssetValidationError) ErrorName() string { return "RemoteAssetValidationError" }

// Error satisfies the builtin error interface
func (e RemoteAssetValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoteAsset.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoteAssetValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoteAssetValidationError{}
