// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: models/remote_connection.proto

package models

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _remote_connection_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on RemoteConnection with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RemoteConnection) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RemoteConnection with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RemoteConnectionMultiError, or nil if none found.
func (m *RemoteConnection) ValidateAll() error {
	return m.validate(true)
}

func (m *RemoteConnection) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	if all {
		switch v := interface{}(m.GetConnectionTarget()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RemoteConnectionValidationError{
					field:  "ConnectionTarget",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RemoteConnectionValidationError{
					field:  "ConnectionTarget",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConnectionTarget()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RemoteConnectionValidationError{
				field:  "ConnectionTarget",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetPermissions() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RemoteConnectionValidationError{
						field:  fmt.Sprintf("Permissions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RemoteConnectionValidationError{
						field:  fmt.Sprintf("Permissions[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RemoteConnectionValidationError{
					field:  fmt.Sprintf("Permissions[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.Id != nil {

		if m.GetId() != "" {

			if err := m._validateUuid(m.GetId()); err != nil {
				err = RemoteConnectionValidationError{
					field:  "Id",
					reason: "value must be a valid UUID",
					cause:  err,
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if m.TenantId != nil {

		if m.GetTenantId() != "" {

			if err := m._validateUuid(m.GetTenantId()); err != nil {
				err = RemoteConnectionValidationError{
					field:  "TenantId",
					reason: "value must be a valid UUID",
					cause:  err,
				}
				if !all {
					return err
				}
				errors = append(errors, err)
			}

		}

	}

	if len(errors) > 0 {
		return RemoteConnectionMultiError(errors)
	}

	return nil
}

func (m *RemoteConnection) _validateUuid(uuid string) error {
	if matched := _remote_connection_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// RemoteConnectionMultiError is an error wrapping multiple validation errors
// returned by RemoteConnection.ValidateAll() if the designated constraints
// aren't met.
type RemoteConnectionMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RemoteConnectionMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RemoteConnectionMultiError) AllErrors() []error { return m }

// RemoteConnectionValidationError is the validation error returned by
// RemoteConnection.Validate if the designated constraints aren't met.
type RemoteConnectionValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RemoteConnectionValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RemoteConnectionValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RemoteConnectionValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RemoteConnectionValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RemoteConnectionValidationError) ErrorName() string { return "RemoteConnectionValidationError" }

// Error satisfies the builtin error interface
func (e RemoteConnectionValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRemoteConnection.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RemoteConnectionValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RemoteConnectionValidationError{}
